package com.example.moqandroid.playback

const val VIDEO_DROP_LATE_US = 250_000L
const val VIDEO_SURFACE_SCHEDULE_AHEAD_US = 50_000L
const val VIDEO_CLOCK_RECHECK_US = 10_000L
const val PLAYBACK_HEAD_POSITION_WRAP = 1L shl 32
const val PLAYBACK_HEAD_POSITION_MASK = PLAYBACK_HEAD_POSITION_WRAP - 1
